apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-react-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-react-app
    spec:
      containers:
      - name: react-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80