name: CI/CD Pipeline on AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build_and_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.5'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test # if you have testing implemented in your project

  Deploy_to_AKS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure ACR Login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.SP_USERNAME }}
          password: ${{ secrets.SP_PASSWORD }}

      - name: Build and Push Docker file
        run: |
          docker build -t ${{ secrets.REGISTRY_NAME }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_NAME }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
      - name: Deploy to AKS
        run: |
          az aks get-credentials --resource-group KubeRG --name myAKSCluster
          helm upgrade --install web-app ./web-app


